//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vIT_System
{
    using System;

    public partial class Fardmedel
    {
        public int FardId { get; set; }
        public string Typ { get; set; }
        public Nullable<int> Milersattning { get; set; }
        public string Kvitto { get; set; }
        public Nullable<int> AId { get; set; }
    
        public virtual Ansokan Ansokan { get; set; }
    }
}
