//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vIT_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forskott
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forskott()
        {
            this.Ansokan = new HashSet<Ansokan>();
        }
    
        public int FId { get; set; }
        public int Summa { get; set; }
        public string Beskrivning { get; set; }
        public Nullable<int> Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ansokan> Ansokan { get; set; }
        public virtual Anstallda Anstallda { get; set; }
    }
}
